### PR TITLE
Case insensitive branch names for git gud test

### LINKED ISSUE #139: Ignore capitalization for user-created branch names
When running `git gud test`, the capitalization of the branch names should be disregarded. For example, if on the `basics-branching` level, the user is prompted to create the branch `bugFix` in one of the steps. If the user creates the branch `BugFix` instead of `bugFix` but does all the other necessary steps correctly, we should accept the solution and deem it solved, instead of rejecting it outright.

### PR DESCRIPTION
**Pull request by sahansk2**
Fixes #139

### CODE REVIEW

**Comment by benthayer** [comment]
I am working on this branch to try and make the testing less obscure. Once I do that, we should be able to fix this

**Comment by benthayer** [comment]
@sahansk2 go ham

**Comment by benthayer** [comment]
@sahansk2 If that was unclear, I mean the API updates and test code refactoring is done and is on the intro branch: https://github.com/benthayer/git-gud/pull/184

**Comment by sahansk2** [comment]
Cool -- I'm going to close this PR, and submit a new one to merge into `intro`.

**Pull request closed without merging**
