### PR TITLE
Fix hook permissions, progress on #79

### LINKED ISSUE #77: Hooks being ignored due to them not being marked as executable
**Describe the bug**
Git hooks do not run when their corresponding git commands are executed in a git-gud directory.

**To Reproduce**
Run `git commit --amend` in an initialized git-gud directory to test the `post-rewrite` hook.

I have run `git gud start` in multiple fresh directories to see if it was a problem with directories already initialized and manipulated with other git commands, but it appears in the fresh directories as well.

**Expected behavior**
The git hooks should run without any problem, and without the user running the suggested command from git to ignore the corresponding warning.

**Screenshots/Output**
`$ git commit --amend`
```
hint: The '.git/hooks/post-rewrite' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
[master 194c4cd] first commit
 Author: Git Gud <git-gud@example.com>
 Date: Sat Oct 26 21:20:50 2019 -0500
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 1
```
**Environment**
OS: Ubuntu 18.04.3 LTS, 64-bit
python Version: 3.6.8
git Version: 2.17.1

### LINKED ISSUE #125: Git hooks (.git/hooks) shellscripts do not have executable permission
Performing a successful rebase does not trigger the post-rewrite hook. Running the hook manually (.git/hooks/<hook_name> in testing directory) gives a permission denied error. Run "chmod +x <hook_name>" to get executable permission. The hook will now run with a successful rebase. 

Need to fix executable permission on these files to make sure users do not have to do this.

See #77 for more details

### PR DESCRIPTION
**Pull request by sahansk2**
Fixes #125 and fixes #77, which are duplicates. Credit goes to @divCurlF for this PR.

This issue has been brought up a second time, and since @divCurlF did most of the fixes already, I just went ahead and implemented them (meaning the rest of them).

Truth to be told, I'm not as confident resolving these merge conflicts, since I didn't author the code, but I can investigate and try resolving them anyway.

### CODE REVIEW

**Comment by benthayer** [comment]
@parkmichael777 Can you test this out and see if fixes things for you?

**Comment by benthayer** [comment]
@sahansk2 Can you merge master into this branch

**Comment by benthayer** [comment]
@parkmichael777 bump, does this work for you?

**Comment by parkmichael777** [comment]
@benthayer I'm going to wait until this is finished so that I don't introduce bugs

**Comment by sahansk2** [comment]
Master's been merged into this branch.

**Comment by benthayer** [comment]
It's fixed, @parkmichael777 go for it

**Comment by parkmichael777** [comment]
@benthayer Looks like it works. Will need to add the stdin pipeline for commitmsg, and change so that pre-commit and pre-rebase use exit condition 1.

**Comment by benthayer** [comment]
Merged because it solves the issue it was meant to solve. @parkmichael777 keep your hook as is, you can overwrite the `precommit.py` here. You can fix the other issues in #131

**Pull request merged**
