### PR TITLE
Fixed `git gud levels` formatting

### LINKED ISSUE #140: Match the formatting for `git gud skills` and `git gud levels`
Here is the current output. `git gud levels` should look like `git gud skills`
```
$ git gud skills
Currently on skill: "basics"

Skill 1 - "basics" : 4 levels
    Level  1 : committing
    Level  2 : branching
    Level  3 : merging
    Level  4 : rebasing
Skill 2 - "rampup" : 4 levels
    Level  1 : detaching
    Level  2 : relrefs1
    Level  3 : relrefs2
    Level  4 : reversing
Skill 3 - "extras" : 1 level
    Level  1 : octopus

Load a level with `git gud load`
$ git gud levels
Levels in the current skill "basics" :

1: committing
2: branching
3: merging
4: rebasing
```

### PR DESCRIPTION
**Pull request by sahansk2**
Fixes #140

### CODE REVIEW

**Comment by benthayer** [comment]
Can you change the double brackets to be something else? I think it makes the code less readable, and we want to make sure all of the code is well-documented and understandable

**Comment by benthayer** [comment]
See 456c995f7aeac410526d5076a19f3e1d4ca95d97

**Comment by benthayer** [comment]
This should be updated with human names. See #185

**Comment by sahansk2** [comment]
Closing this PR because #185 will fix this.

**Pull request closed without merging**
