### PR TITLE
Level `git init`

### LINKED ISSUE #212: Level: `git init`
Show off the `git init` command

### PR DESCRIPTION
**Pull request by benthayer**
Add a few intro levels...
The following updates were merged with #211:
 - `git gud test`
 - `git gud status`
 - `git gud load next`
 - `git config --global user.name`
 - `git config --global user.email`

Here, we are working on:
 - `git init`

Closes #212

### CODE REVIEW

**Comment by benthayer** [comment]
- Tests are failing, a method is not implemented

 - People will forget git log and will probably try to do run something like git gud help to figure out what they should be running. We need to hold their hand longer than we currently do.

 - People will also likely be expecting `git gud status` to be showing them  `git log` anyways

 - We do not have a use for `git gud status` in most levels, the relevant information is shown right away. Should we wait to show this information? I think that would make `git gud status` more useful later on. 

 - @sahansk2 What do you think of this:

```
[user@laptop] $ git gud load next
Skill: The Basics                 (basics)
Level: Your First Commit          (committing)

Goal: Commit twice
[user@laptop] $ git gud status
# What we had before
```

@sahansk2 Can you elaborate your thoughts on the spacing issues we've talked about? Do you have any other comments?

**Comment by benthayer** [comment]
We will implement these human names later, hopefully soon #185

**Comment by sahansk2** [comment]
The more I think about it, the more I think having things closer together is fine in general. For example, when the working tree is clean and there aren't any commands to output, and `git status` is run, the output is packed together:
```
[user@laptop] $ git status
On branch master
nothing to commit, working tree clean
[user@laptop] $
```
For me, in general, having things closer together isn't that inconvenient: more so, it's having to scroll through the terminal in order to recall certain output directions because the output is more spaced out. 

There are limits to this though: I think putting line breaks for (1) separating readable text output [paragraphs] into blocks is fine, and I think putting line breaks for (2) commands if we're explaining them is also fine. (For reference, I'm looking at the output of `git help` for (1), which groups commands based on types of tasks, and I'm looking at the output of `git push` in a fresh directory for (2), where it explains what commands should be used to set upstream and whatnot).

I also think that putting line breaks for (3) padding git-specific output within delimiters is fine too. See below example output: 
(Note: I use `git gud commit` as an example of a git gud command without any notable git output, and `git gud baz` as an example of a git gud command with notable git output that should be padded).
```
[user@laptop] $ git gud load next
Skill: The Basics                 (basics)
Level: Your First Commit          (committing)

Goal: Commit twice on the master branch. For more foo, type in `git gud bar`.
After bar'ing, qux three times on bugFix.

This sentence is only here to illustrate the use of a line break to separate written 
text from other useful output or unrelated paragraphs.
[user@laptop] $ git gud commit 
<<<<<<< Simulating: Create file "2"
<<<<<<< Simulating: git add 2
<<<<<<< Simulating: git commit -m "2"
[INFO]: New Commit: abcdef123 
[user@laptop] $ git gud baz 
<<<<<<< Simulating: git log --graph --oneline --all

* abcdef123 (HEAD -> master) 1

=======
[user@laptop] $
```
You could probably tell, but I really *really* like the git-merge-conflict-style delimiters :upside_down_face:...but of course, whatever delimiter gets the job done the best is what we should use. 
What do you think, @benthayer ?

**Comment by benthayer** [comment]
Waiting for #202 to be solved

**Comment by benthayer** [comment]
> The more I think about it, the more I think having things closer together is fine in general. For example, when the working tree is clean and there aren't any commands to output, and `git status` is run, the output is packed together:
> 
> ```
> [user@laptop] $ git status
> On branch master
> nothing to commit, working tree clean
> [user@laptop] $
> ```
> 
> For me, in general, having things closer together isn't that inconvenient: more so, it's having to scroll through the terminal in order to recall certain output directions because the output is more spaced out.
> 
> There are limits to this though: I think putting line breaks for (1) separating readable text output [paragraphs] into blocks is fine, and I think putting line breaks for (2) commands if we're explaining them is also fine. (For reference, I'm looking at the output of `git help` for (1), which groups commands based on types of tasks, and I'm looking at the output of `git push` in a fresh directory for (2), where it explains what commands should be used to set upstream and whatnot).
> 
> I also think that putting line breaks for (3) padding git-specific output within delimiters is fine too. See below example output:
> (Note: I use `git gud commit` as an example of a git gud command without any notable git output, and `git gud baz` as an example of a git gud command with notable git output that should be padded).
> 
> ```
> [user@laptop] $ git gud load next
> Skill: The Basics                 (basics)
> Level: Your First Commit          (committing)
> 
> Goal: Commit twice on the master branch. For more foo, type in `git gud bar`.
> After bar'ing, qux three times on bugFix.
> 
> This sentence is only here to illustrate the use of a line break to separate written 
> text from other useful output or unrelated paragraphs.
> [user@laptop] $ git gud commit 
> <<<<<<< Simulating: Create file "2"
> <<<<<<< Simulating: git add 2
> <<<<<<< Simulating: git commit -m "2"
> [INFO]: New Commit: abcdef123 
> [user@laptop] $ git gud baz 
> <<<<<<< Simulating: git log --graph --oneline --all
> 
> * abcdef123 (HEAD -> master) 1
> 
> =======
> [user@laptop] $
> ```
> 
> You could probably tell, but I really _really_ like the git-merge-conflict-style delimiters upside_down_face...but of course, whatever delimiter gets the job done the best is what we should use.
> What do you think, @benthayer ?

Referencing all this for #185

#185 supercedes conversation here

**Comment by benthayer** [comment]
We should implement a level for `git clone` before we merge this, or at least, we should reference it. Shouldn't be hard once #202 is done

**Pull request merged**
