### PR TITLE
Implement `git gud load next`

### LINKED ISSUE #31: Remove `git gud progress` and replace with `git gud load next`
People read progress as if it is the noun, when I originally meant it to be the verb. That is confusing, so I think it would be good to make loading the next level a special case of the `load` subcommand.

We'll also need to make sure we change the instructions to match this change, so nobody types in `git gud progress` expecting to load the next level

Relevant methods are `handle_progress` and `handle_load` in `gitgud/__main__.py`

### PR DESCRIPTION
**Pull request by TSSlade**
fixes #31

### CODE REVIEW

**Comment by benthayer** [comment]
Hey @TSSlade, you're pretty close to getting this PR done, just two things:
 - [ ] Update readme
 - [ ] Display tree after loading

Do you think you can get these done?

Also, if I recall, you also started doing some work on #49. If you'd like to keep working on that and open up a PR, that'd be great!

**Comment by benthayer** [comment]
Hey @TSSlade I appreciate the work you've done so far. I'm trying to wrap up some features, so if you don't respond by Friday, I'll finish this up and get it merged

**Comment by benthayer** [comment]
@sahansk2 Do you want to finish this up?

**Comment by sahansk2** [comment]
@benthayer Sure thing -- the code in this branch seems to be a bit older, so I'll probably start a new PR from scratch.
Also, a clarification -- if somebody finished all the challenges in a skill, should `git gud load next` bring them to the first challenge of the next skill?

**Comment by benthayer** [comment]
Feel free to do whatever to keep the work. Keep in mind that you can do `git pull --rebase` so it's not a giant merge coming in.

To answer your question, yes, `git gud load next` should load the first level of the next skill

**Comment by benthayer** [comment]
#134 has fixed this issue. Closing

**Pull request closed without merging**
