### PR TITLE
Terminal "live" demonstration in README.md

### LINKED ISSUE #73: Use asciinema in readme to show how the levels work
Thanks to @Byron for the suggestion. Here's the link to the original comment and to aciinema

https://github.com/gitpython-developers/GitPython/pull/951
https://asciinema.org/

It would be great to show users how to use Git Gud before they download it, that way it comes off as more accessible and people know what they're getting into.

### PR DESCRIPTION
**Pull request by sahansk2**
Fixes #73 .

The asciinema [preview](https://asciinema.org/a/bNwZf8ZCVqSV4f7ivQqwjFPuq
) is completed, and is now in the README.md file.

A particular caveat of asciinema, though, is that the animated preview can't be embedded in the README.md file -- you have to be taken to asciinema.org in order to see it in action.

We can convert the asciinema file to a gif with [asciicast2gif](https://github.com/asciinema/asciicast2gif), and embed that -- should I go ahead and do so?

EDIT: [Here](https://imgur.com/lOJfpox) is a compiled GIF.

### CODE REVIEW

**Comment by benthayer** [comment]
gif seems of low quality, any way you can improve that?

**Comment by sahansk2** [comment]
I can increase the scale to the default setting (2), which looked a bit cleaner when I saw it: here's the [result](https://imgur.com/a/7wVOrMx).

If it's still not clean enough, we could alternatively use [termtosvg](https://github.com/nbedos/termtosvg), which I think might look sharper due to it being an SVG file.

**Comment by benthayer** [comment]
New gif looks good, wanna stick it in?

**Comment by sahansk2** [comment]
Sure, I'll replace the asciinema preview with the GIF and push the commit.

**Pull request merged**
